version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_bench
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "2GB"

  postgres:
    image: postgres:latest
    container_name: postgres_bench
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "5GB"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo_bench
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "5GB"
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
